### ISSUE TITLE
Problem determining nnmax for slabs

### ISSUE THREAD

**Issue by alanmlewis** [dilkins/SOAPFAST-public#14]
Line 73 of get_power_spectrum.py determines the maximum atomic density (number of atoms / cell volume) in the series of frames in order to estimate a safe maximum number of possible nearest neighbours in periodic structures.

However, for slabs with a large vacuum region this fails, as the maximum atomic density is artificially lowered by the vacuum region, making it hard to define a "safe" upper bound for n. This leads to segmentation faults in initsoap.pyx, due to out-of-bounds access to arrays with an upper bound of nnmax on some axis (e.g. "length", "efact", "harmonic").

I'm afraid it's not obvious to me what the best solution to this is, given that the size of a vacuum region is largely arbitrary - possibly simply a 'slab' flag which can be set at runtime which sets nnmax = 100?

**Comment by dilkins** [comment]
This might be the best option; when writing the code originally, there was quite a bit of flipping between setting a hard `nnmax`, which is "safe" but often slow, and setting one by calculating the density, which is faster but only really works for systems with uniform density; having a flag that sets `nnmax` to a hard limit is inelegant (especially as `sagpr_get_PS` has so many command-line flags already), but it's probably the best option. Feel free @alanmlewis to implement and open a PR -- otherwise I will be able to get to it in a couple of days' time.

**Comment by alanmlewis** [comment]
Another possibility would be to offer a flag where the user could set the occupied fraction of the cell at runtime, and then simply multiply the volume by this fraction? That may require a little trial and error on the user's part, but is more flexible than simply setting a hard limit.

**Comment by dilkins** [comment]
Agreed, that's probably a better idea; since we're admitting trial and error, probably some extra exception handling is needed so that the code doesn't crash so messily.

**Comment by alanmlewis** [comment]
Yes. for sure; I'll have a go at implementing that tomorrow.

**Comment by alanmlewis** [comment]
Resolved by commit [f448a04](https://github.com/dilkins/TENSOAP/commit/f448a04f1a91fb8ed0bd43ea877e7bef0f2b220e)
